# Generated by Django 5.1.1 on 2024-09-11 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('position', models.CharField(choices=[('open', 'Open'), ('open_palm', 'Open Palm'), ('sensual', 'Sensual'), ('close', 'Close')], max_length=100)),
                ('s_handhold', models.CharField(choices=[('h1', 'H1'), ('h2,', 'H2')], max_length=100)),
                ('e_handhold', models.CharField(choices=[('h1', 'H1'), ('h2,', 'H2')], max_length=100)),
                ('level', models.IntegerField(choices=[('Beginner', 1), ('Beginner Advanced', 2)])),
            ],
        ),
    ]
