# Generated by Django 5.1.1 on 2024-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='level',
            field=models.IntegerField(choices=[('1', 'Beginner'), ('2', 'Beginner Advanced')]),
        ),
    ]
