# Generated by Django 5.1.1 on 2024-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_alter_move_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Beginner Advanced', 'Beginner Advanced')], max_length=25),
        ),
    ]
