# Generated by Django 5.1.1 on 2024-09-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0003_alter_move_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handhold', models.CharField(choices=[('h1', 'H1'), ('h2,', 'H2')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='e_handhold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_handhold', to='bpm.handhold'),
        ),
        migrations.AlterField(
            model_name='move',
            name='s_handhold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_handhold', to='bpm.handhold'),
        ),
        migrations.CreateModel(
            name='MoveMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handHold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpm.handhold')),
            ],
        ),
    ]
