# Generated by Django 5.1.1 on 2024-09-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0004_handhold_alter_move_e_handhold_alter_move_s_handhold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='end_handhold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_handhold', to='bpm.handhold'),
        ),
        migrations.AddField(
            model_name='move',
            name='start_handhold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_handhold', to='bpm.handhold'),
        ),
        migrations.AlterField(
            model_name='move',
            name='e_handhold',
            field=models.CharField(choices=[('h1', 'H1'), ('h2,', 'H2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='move',
            name='s_handhold',
            field=models.CharField(choices=[('h1', 'H1'), ('h2,', 'H2')], max_length=100),
        ),
    ]
