# Generated by Django 5.1.1 on 2024-09-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0005_move_end_handhold_move_start_handhold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='end_handhold',
        ),
        migrations.RemoveField(
            model_name='move',
            name='start_handhold',
        ),
    ]
