# Generated by Django 5.1.1 on 2024-09-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0006_remove_move_end_handhold_remove_move_start_handhold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoveMatrix',
        ),
    ]
