# Generated by Django 5.1.1 on 2024-09-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0007_delete_movematrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='e_handhold',
        ),
        migrations.RemoveField(
            model_name='move',
            name='s_handhold',
        ),
    ]
