# Generated by Django 5.1.1 on 2024-09-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0008_remove_move_e_handhold_remove_move_s_handhold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
