# Generated by Django 5.1.1 on 2024-09-11 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0009_delete_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('position', models.CharField(choices=[('open', 'Open'), ('open_palm', 'Open Palm'), ('sensual', 'Sensual'), ('close', 'Close')], max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Beginner Advanced', 'Beginner Advanced')], max_length=25)),
                ('end_handhold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_handhold', to='bpm.handhold')),
                ('start_handhold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_handhold', to='bpm.handhold')),
            ],
        ),
    ]
