# Generated by Django 5.1.1 on 2024-09-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0010_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='handhold',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
