# Generated by Django 5.1.1 on 2024-09-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0011_handhold_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handHold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpm.handhold')),
                ('moveKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpm.move')),
            ],
        ),
    ]
