# Generated by Django 5.1.1 on 2024-09-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0012_movematrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handhold',
            name='handhold',
            field=models.CharField(choices=[('h1', 'H1'), ('h2', 'H2')], max_length=25),
        ),
    ]
