# Generated by Django 5.1 on 2024-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0013_alter_handhold_handhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
