# Generated by Django 5.1 on 2024-09-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0014_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='new_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpm.position'),
        ),
    ]
