# Generated by Django 5.1.1 on 2024-09-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0017_remove_move_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handhold',
            name='handhold',
            field=models.CharField(max_length=25),
        ),
    ]
