# Generated by Django 5.1.1 on 2024-09-16 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0018_alter_handhold_handhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='movematrix',
            name='count',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
