# Generated by Django 5.1.1 on 2024-09-16 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0019_movematrix_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movematrix',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
